name: CI

on: ["push"]

jobs:
  run-tests:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    env:
      APP_ENV: local
      DB_HOST: 127.0.0.1
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: test
    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.1"]
    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          tools: pecl

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-suggest

      # - name: Run Kanvas Migrations
      #   if: success()
      #   run: php artisan migrate

      # - name: Run Pest Unit Tests Group
      #   if: success()
      #   run: vendor/bin/pest --group=unit

      # - name: Run Pest Feature Tests Group
      #   if: success()
      #   run: vendor/bin/pest --group=feature
